;;; Automatically generated by ‘recentf’ on Fri Oct 31 21:13:00 2025.

(setq recentf-list
      '(
        "~/Downloads/a.scala"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
