;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history yes-or-no-p-history counsel-M-x-history))
(setq file-name-history '(#("/Users/Fomo/Downloads/" 0 22 (ivy-index 2))))
(setq yes-or-no-p-history '("yes"))
(setq counsel-M-x-history '(#("^nerd-icons-install" 0 19 (ivy-index 0)) "nerd-icons-install-fonts" #("^all-the-icons-install" 0 22 (ivy-index 0)) "all-the-icons-install-fonts"))
(setq tablist-named-filter 'nil)
(setq projectile-project-command-history '#s(hash-table test equal))
(setq evil-jumps-history '((129 "~/Downloads/")))
